bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from books.views import index

urlpatterns = [
    url(r'^$',index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^book/',include('books.urls',namespace='books')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^comment/',include('comments.urls',namespace='comment')),
    url(r'^search/', include('haystack.urls')),

]

cart/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add/$', cart_add, name='add'),  # 添加购物车数据
    url(r'^count/$',cart_count, name='count'),  # 获取用户购物车中商品的数量
    url(r'^$',cart_show,name='show'),
    url(r'^del/$',cart_del,name='delete'),
    url(r'^update/$',cart_update,name='update'),
]

order/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^place/$',order_place,name='place'),
    url(r'^commit/$',order_commit,name='commit'),
    url(r'^pay/$', order_pay, name='pay'),
    url(r'^check_pay/$', check_pay, name='check_pay'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django_redis import get_redis_connection

from books.models import Books
from utils.decorators import login_required


@login_required
def cart_add(request):
    books_id = request.POST.get('books_id')
    books_count = request.POST.get('books_count')
    if not all([books_id,books_count]):
        return JsonResponse({'res':1,'errmsg':'数据不完整'})
    books = Books.objects.get_books_by_id(books_id=books_id)
    if not books:
        return JsonResponse({'res':2,'errmsg':'商品不存在'})

    try:
        books_count = int(books_count)
    except Exception as e:
        # 商品数目不合法
        return JsonResponse({'res': 3, 'errmsg': '商品数量必须为数字'})

    connect_redis = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('passport_id')
    res = connect_redis.hget(cart_key, books_id)
    if res is None:
        # 如果用户的购车中没有添加过该商品，则添加数据
        res = books_count
    else:
        # 如果用户的购车中已经添加过该商品，则累计商品数目
        res = int(res) + books_count

    # 判断商品的库存
    if res > books.stock:
        # 库存不足
        return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
    else:
        connect_redis.hset(cart_key, books_id, res)

    # 返回结果
    return JsonResponse({'res': 5,'errmsg':'成功加入购物车！'})

@login_required
def cart_count(request):
    '''获取用户购物车中商品的总数'''
    connetion = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('passport_id')
    res_list = connetion.hvals(cart_key)
    res = 0
    for i in res_list:
        res += int(i)
    return JsonResponse({'res':res})

@login_required
def cart_show(request):
    '''显示购物车页面'''
    passport_id = request.session.get('passport_id')
    connection = get_redis_connection('default')
    cart_key = 'cart_%d'%passport_id
    res_dict = connection.hgetall(cart_key)
    books_li = []
    total_count = 0
    total_price = 0
    for id,count in res_dict.items():
        books = Books.objects.get_books_by_id(books_id=id)
        books.count = count
        books.amount = int(count)*books.price
        books_li.append(books)
        total_count += int(count)
        total_price += int(count)*books.price

    context = {
        'books_li':books_li,
        'total_count':total_count,
        'total_price':total_price
    }
    return render(request,'cart/cart.html',context)


@login_required
def cart_del(request):
    '''删除购物车中额商品'''
    books_id = request.POST.get('books_id')
    if not books_id:
        return JsonResponse({'res':1,'errmsg':'数据不完整'})
    books = Books.objects.get_books_by_id(books_id)
    if not books:
        return JsonResponse({'res':2,'errmsg':'商品不存在'})
    connection = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('passport_id')
    connection.hdel(cart_key,books_id)
    return JsonResponse({'res':3})

@login_required
def cart_update(request):
    '''更新购物车商品数目'''
    # 接收数据
    books_id = request.POST.get('books_id')
    books_count = request.POST.get('books_count')
    # 数据的校验
    if not all([books_id, books_count]):
        return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
    books = Books.objects.get_books_by_id(books_id=books_id)
    if books is None:
        return JsonResponse({'res': 2, 'errmsg': '商品不存在'})
    try:
        books_count = int(books_count)
    except Exception as e:
        return JsonResponse({'res': 3, 'errmsg': '商品数目必须为数字'})
    # 更新操作
    conn = get_redis_connection('default')
    cart_key = 'cart_%d' % request.session.get('passport_id')
    # 判断商品库存
    if books_count > books.stock:
        return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
    conn.hset(cart_key, books_id, books_count)
    return JsonResponse({'res': 5})

templates/cart/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}购物车{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/del_cart.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="total_count">全部商品<em>{{ books_li|length }}</em>类</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    <form method="post" action="{% url 'order:place' %}">
    {% for book in books_li %}
        <ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="books_ids" value="{{ book.id }}" checked></li>
		<li class="col02"><img src="{% static book.image %}"></li>
		<li class="col03">{{ book.name }}<br><em>{{ book.price }}元</em></li>
		<li class="col04">{{ book.unit }}</li>
		<li class="col05">{{ book.price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" books_id="{{ book.id }}" class="num_show fl" value="{{ book.count }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ book.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	    </ul>
    {% endfor %}
	<ul class="settlements">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock body %}