books/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^index',index,name='index'),
    url(r'books/(?P<books_id>\d+)/$',detail,name='detail'),
    url(r'list/(?P<type_id>\d+)/(?P<page>\d+)/$',list,name='list'),
]

bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from books.views import index

urlpatterns = [
    url(r'^$',index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^book/',include('books.urls',namespace='books')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^comment/',include('comments.urls',namespace='comment')),
    url(r'^search/', include('haystack.urls')),

]

cart/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add/$', cart_add, name='add'),  # 添加购物车数据
    url(r'^count/$',cart_count, name='count'),  # 获取用户购物车中商品的数量
    url(r'^$',cart_show,name='show'),
    url(r'^del/$',cart_del,name='delete'),
    url(r'^update/$',cart_update,name='update'),
]

books/models.py
from django.db import models

from db.base_model import BaseModel
from tinymce.models import HTMLField
from books.enums import *

class BooksManager(models.Manager):
    '''商品模型管理器类'''
    # sort='new' 按照创建时间进行排序
    # sort='hot' 按照商品销量进行排序
    # sort='price' 按照商品的价格进行排序
    # sort= 按照默认顺序排序
    def get_books_by_type(self, type_id, limit=None, sort='default'):
        '''根据商品类型id查询商品信息'''
        if sort == 'new':
            order_by = ('-creare_time',)
        elif sort == 'hot':
            order_by = ('-sales', )
        elif sort == 'price':
            order_by = ('price', )
        else:
            order_by = ('-id', ) # 按照primary key降序排列。

        # 查询数据
        books_li = self.filter(type_id=type_id).order_by(*order_by)

        # 查询结果集的限制
        if limit:
            books_li = books_li[:limit]
        return books_li

    def get_books_by_id(self, books_id):
        '''根据商品的id获取商品信息'''
        try:
            books = self.get(id=books_id)
        except self.model.DoesNotExist:
            # 不存在商品信息
            books = None
        return books

class Books(BaseModel):
    '''商品模型类'''
    books_type_choices = ((k, v) for k,v in BOOKS_TYPE.items())
    status_choices = ((k, v) for k,v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON, choices=books_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=64, verbose_name='商品名称')
    desc = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unit = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')
    create_time = models.DateField(default='2018-8-18',verbose_name='创建时间')

    objects = BooksManager()

    # admin显示书籍的名字
    def __str__(self):
        return self.name

    class Meta:
        db_table = 's_books'
        verbose_name = '书籍'
        verbose_name_plural = '书籍'

books/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page
from django_redis import get_redis_connection
import logging

from .models import Books
from .enums import *

logger = logging.getLogger('django.request')


'''显示首页'''
# @cache_page(60*10)  #缓存首页
def index(request):

    #当我们访问首页的时候，在log/debug.log中有日志信息
    logger.info(request.body)

    # 查询每个种类的3个新品信息和4个销量最好的商品信息
    python_new = Books.objects.get_books_by_type(PYTHON, limit=3, sort='new')
    python_hot = Books.objects.get_books_by_type(PYTHON, limit=4, sort='hot')
    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT, limit=3, sort='new')
    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT, limit=4, sort='hot')
    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS, 3, sort='new')
    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS, 4, sort='hot')
    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING, 3, sort='new')
    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING, 4, sort='hot')
    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM, 3, sort='new')
    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM, 4, sort='hot')
    database_new = Books.objects.get_books_by_type(DATABASE, 3, sort='new')
    database_hot = Books.objects.get_books_by_type(DATABASE, 4, sort='hot')
    # 定义模板上下文
    context = {
        'python_new': python_new,
        'python_hot': python_hot,
        'javascript_new': javascript_new,
        'javascript_hot': javascript_hot,
        'algorithms_new': algorithms_new,
        'algorithms_hot': algorithms_hot,
        'machinelearning_new': machinelearning_new,
        'machinelearning_hot': machinelearning_hot,
        'operatingsystem_new': operatingsystem_new,
        'operatingsystem_hot': operatingsystem_hot,
        'database_new': database_new,
        'database_hot': database_hot,
    }
    # 使用模板
    return render(request, 'books/index.html', context)

'''商品详情'''
def detail(request,books_id):

    books =Books.objects.get_books_by_id(books_id=books_id)
    if not books:
        return redirect(reverse('books:index'))
    #新品推荐
    books_li = Books.objects.get_books_by_type(type_id=books.type_id,limit=2,sort='new')

    # 用户登录之后，才记录浏览记录
    # 每个用户浏览记录对应redis中的一条信息 格式:'history_用户id':[10,9,2,3,4]
    # [9, 10, 2, 3, 4]
    if request.session.has_key('islogin'):
        # 用户已登录，记录浏览记录
        con = get_redis_connection('default')
        key = 'history_%d' % request.session.get('passport_id')
        # 先从redis列表中移除books.id
        con.lrem(key, 0, books.id)
        con.lpush(key, books.id)
        # 保存用户最近浏览的5个商品
        con.ltrim(key, 0, 4)

    '''当前商品类型'''
    type_title = BOOKS_TYPE[books.type_id]
    return render(request,'books/detail.html',{'books':books,'books_li':books_li,'type_title':type_title})

def list(request,type_id,page):

    '''商品列表界面'''
    sort = request.GET.get('sort','default')
    #判断type——id是否合法
    if int(type_id) not in BOOKS_TYPE.keys():
        return redirect(reverse('books:index'))
    books_li =Books.objects.get_books_by_type(type_id=type_id,sort=sort)
    #实例分页，设置每页书籍数量:3
    paginator = Paginator(books_li,3)
    #.num_pages属性获取总页数
    num_pages = paginator.num_pages
    #判断传入参数page
    if page=='' or int(page) > num_pages or int(page) < 1:
        page=1
    else:
        page = int(page)

    #返回一个page类实例对象，包含一页所有书籍的可迭代对象
    books_li =paginator.page(page)
    ''' 根据当前page,控制页面导航条范围pages
        1.总页数<5, 显示所有页码
        2.当前页是前3页，显示1-5页
        3.当前页是后3页，显示后5页 10 9 8 7
        4.其他情况，显示当前页前2页，后2页，当前页'''
    if num_pages < 5:
        pages = range(1,num_pages)
    elif page < 4:
        pages = range(1,6)
    elif num_pages - page <=2:
        pages = range(num_pages-4,num_pages+1)
    else:
        pages = range(page-2,page+3)
    #新品推荐
    book_new = Books.objects.get_books_by_type(type_id=type_id,limit=2,sort='new')
    #设置上下文
    type_title = BOOKS_TYPE[int(type_id)]
    context = {
        'books_li':books_li,
        'book_new':book_new,
        'type_id':type_id,
        'sort':sort,
        'type_title':type_title,
        'pages':pages
    }
    return render(request,'books/list.html',context)

templates/books/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}阶梯书店-商品详情{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/detail_price.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/add_cart.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/comment.js' %}"></script>
    <style>
        .comment {
            background-color: #c40000;
            color: #fff;
            margin-left: 10px;
            position: relative;
            z-index: 10;
            display: inline-block;
            width: 178px;
            height: 38px;
            border: 1px solid #c40000;
            font-size: 14px;
            line-height: 38px;
            text-align: center;
        }
    </style>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'books:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type_title }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="book_detail_con clearfix">
		<div class="book_detail_pic fl"><img src="{% static books.image %}"></div>

		<div class="book_detail_list fr">
			<h3>{{ books.name }}</h3>
			<p>{{ books.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ books.price }}</em></span>
				<span class="show_unit">单  位：{{ books.unit }}</span>
			</div>
			<div class="book_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>100元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" books_id="{{ books.id }}" class="add_cart" id="add_cart">加入购物车</a>
                <a href="#detail" id="write-comment" class="comment">我要写评论</a>
			</div>

		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in books_li %}
					<li>
						<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active" id="detail">商品介绍</li>
				<li id="comment">评论</li>
			</ul>

			<div class="tab_content">
				<dl id="book_detail">
					<dt>商品详情：</dt>
					<dd>{{ books.detail|safe }}</dd>
				</dl>
                <dl id="book_comment" style="display: none; font-size: 15px; color: #0a0a0a">
                    <dt>用户评论:</dt>
                    <dd></dd>
                </dl>
			</div>

            <div style="display:none;" id="comment-input" data-bookid="{{ books.id }}" data-userid="{{ request.session.passport_id }}">
                <div>
                    <input type="text" placeholder="评论内容">
                </div>
                <div id="submit-comment">
                    <button>
                      提交评论
                    </button>
                </div>
            </div>

		</div>
	</div>
    <div class="add_jump"></div>
{% endblock body%}

templates/books/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}阶梯书店-商品列表{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js'%}"></script>
{% endblock topfiles %}	#引入文件块
{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'books:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'images/slide.jpg'%}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide02.jpg'%}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide03.jpg'%}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="{% static 'images/slide04.jpg'%}" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
{#				<a href="#">Python核心编程</a>#}
{#				<a href="#">笨办法学Python</a>#}
{#				<a href="#">Python学习手册</a>#}
                {% for pybook in python_new %}
                    <a href="#">{{ pybook.name }}</a>
                {% endfor %}

			</div>
			<a href="{% url 'books:list' 1 1 %}" class="book_more fr">查看更多 ></a>
		    </div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="book_list fl">
                {% for pybook in python_hot %}
                    <li>
					<h4><a href="{% url 'books:detail' books_id=pybook.id %}">{{ pybook.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=pybook.id %}"><img src="{% static pybook.image %}"></a>
					<div class="prize">¥ {{ pybook.price }}</div>
				    </li>
                {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for jsbook in javascript_new %}
                    <a href="#">{{ jsbook.name }}</a>
                {% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
			<ul class="book_list fl">
				{% for jsbook in javascript_hot %}
				    <li>
					<h4><a href="{% url 'books:detail' books_id=jsbook.id %}">{{ jsbook.name }}</a></h4>
					<a href="{% url 'books:detail' books_id=jsbook.id %}"><img src="{%  static  jsbook.image %}"></a>
					<div class="prize">¥ {{ jsbook.price }}</div>
				    </li>
				{% endfor %}

			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for book in algorithms_new %}
                    <a href="">{{ book.name }}</a>
				{% endfor %}

			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in algorithms_hot %}
				    <li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for book in machinelearning_new %}
                    <a href="#">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in machinelearning_hot %}
				    <li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for book in operatingsystem_new %}
                    <a href="#">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in operatingsystem_hot %}
				    <li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库新书：</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for book in database_new %}
                    <a href="#">{{ book.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
			<ul class="book_list fl">
				{% for book in database_hot %}
				    <li>
					<h4><a href="#">{{ book.name }}</a></h4>
					<a href="#"><img src="{% static book.image %}"></a>
					<div class="prize">¥ {{ book.price }}</div>
				    </li>
				{% endfor %}
			</ul>
		</div>
	</div>

{% endblock body%}

templates/books/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}阶梯书店-商品列表{% endblock title %}
{% block topfiles %}

{% endblock topfiles %}	#引入文件块
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="python">Python</a></li>
					<li><a href="#" class="javascript">Javascript</a></li>
					<li><a href="#" class="algorithms">数据结构与算法</a></li>
					<li><a href="#" class="machinelearning">机器学习</a></li>
					<li><a href="#" class="operatingsystem">操作系统</a></li>
					<li><a href="#" class="database">数据库</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'books:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">Python</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_book">
				<h3>新品推荐</h3>
				<ul>
                    {% for book in book_new %}
                        <li>
						<a href="{% url 'books:detail' books_id=book.id %}"><img src="{% static book.image %}"></a>
						<h4><a href="{% url 'books:detail' books_id=book.id %}">{{ book.name }}</a></h4>
						<div class="prize">￥{{ book.price }}</div>
					    </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'books:list' type_id=type_id page=1 %}" {% if sort == 'default' %}class="active" {% endif %}>默认</a>
				<a href="{% url 'books:list' type_id=type_id page=1 %}?sort=price" {% if sort == 'price' %}class="active" {% endif %}>价格</a>
                <a href="{% url 'books:list' type_id=type_id page=1 %}?sort=hot" {% if sort == 'hot' %}class="active" {% endif %}>人气</a>

			</div>

			<ul class="book_type_list clearfix">
				{% for books in books_li %}
                    <li>
                        <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
                        <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
                        <div class="operate">
                            <span class="price">￥{{ books.price }}</span>
                            <span class="unit">{{ books.unit }}</span>
                            <a href="#" class="add_books" title="加入购物车"></a>
                        </div>
                     </li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if books_li.has_previous %} #通过类属性判断是否显示上一页链接
                    <a href="{% url 'books:list' type_id=type_id page=books_li.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for mypage in pages %}
                    {% if mypage in pages %}
                        <a href="{% url 'books:list' type_id=type_id page=mypage %}?sort={{ sort }}" class="active">{{ mypage }}</a>
                    {% else %}
                        <a href="{% url 'books:list' type_id=type_id page=mypage %}?sort={{ sort }}">{{ mypage }}</a>
                    {% endif %}
                {% endfor %}
                {% if  books_li.has_next %}
                    <a href="{% url 'books:list' type_id=type_id page=books_li.next_page_number %}?sort={{ sort }}">下一页</a>
                {% endif %}

			</div>
		</div>
	</div>
{% endblock body %}
	