books/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^index',index,name='index'),
    url(r'books/(?P<books_id>\d+)/$',detail,name='detail'),
    url(r'list/(?P<type_id>\d+)/(?P<page>\d+)/$',list,name='list'),
]

bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from books.views import index

urlpatterns = [
    url(r'^$',index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^book/',include('books.urls',namespace='books')),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^comment/',include('comments.urls',namespace='comment')),
    url(r'^search/', include('haystack.urls')),

]

cart/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add/$', cart_add, name='add'),  # 添加购物车数据
    url(r'^count/$',cart_count, name='count'),  # 获取用户购物车中商品的数量
    url(r'^$',cart_show,name='show'),
    url(r'^del/$',cart_del,name='delete'),
    url(r'^update/$',cart_update,name='update'),
]

users/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^register/$',register,name='register'),
    url(r'login/$',login,name='login'),
    url(r'logout/$',logout,name='logout'),
    url(r'^center/$',center,name='center'),
    url(r'^address/$',address,name='address'),
    url(r'^order/(?P<page>\d+)/$',order,name='order'),
    url(r'^verifycode/$',verifycode,name='verifycode'),
    url(r'^active/(?P<token>.*)/$', register_active, name='active'), # 用户激活
]

users/models.py
from django.db import models

from db.base_model import BaseModel
from utils import get_hash

# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self,username,password,email):
        passport = self.create(username=username,password=get_hash(password),email=email)
        return passport
    def get_one_passport(self,username,password):
        try:
            passport = self.get(username=username,password=get_hash(password))
        except self.model.DoesNotExist:
            passport=None
        return passport

class Passport(BaseModel):
    '''用户模型类'''
    username = models.CharField(max_length=20, unique=True, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')

    # 用户表的管理器
    objects = PassportManager()

    class Meta:
        db_table = 's_user_account' #自定义表名
        verbose_name = '用户'
        verbose_name_plural = '用户'


class AddressManager(models.Manager):
    '''地址模型管理器类'''

    def get_default_address(self, passport_id):
        '''查询指定用户的默认收货地址'''
        try:
            addr = self.get(passport_id=passport_id, is_default=True)
        except self.model.DoesNotExist:
            # 没有默认收货地址
            addr = None
        return addr

    def add_one_address(self, passport_id, recipient_name, recipient_addr, zip_code, recipient_phone):
        '''添加收货地址'''
        # 判断用户是否有默认收货地址
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            # 存在默认地址
            is_default = False
        else:
            # 不存在默认地址
            is_default = True

        # 添加一个地址
        addr = self.create(passport_id=passport_id,
                           recipient_name=recipient_name,
                           recipient_addr=recipient_addr,
                           zip_code=zip_code,
                           recipient_phone=recipient_phone,
                           is_default=is_default)
        return addr

    def check_passport(self, username):
        try:
            passport = self.get(username=username)
        except self.model.DoesNotExist:
            passport = None
        if passport:
            return True
        return False

class Address(BaseModel):
    '''地址模型'''
    recipient_name = models.CharField(max_length=32,verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code = models.CharField(max_length=6,verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认')
    passport = models.ForeignKey('Passport',verbose_name='账户')

    objects = AddressManager()

    class Meta:
        db_table = 's_user_address'
        verbose_name = '地址'
        verbose_name_plural = '地址'

users/views.py
import random
import re
import io
import os
from django.conf import settings
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from PIL import Image,ImageDraw,ImageFont
from django.http import HttpResponse
from django_redis import get_redis_connection
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired

from books.models import Books
from .models import Passport,Address
from utils.decorators import login_required
from order.models import OrderInfo,OrderGoods
from bookstore.settings import BASE_DIR
from users.tasks import send_active_email

'''注册'''
def register(request):
    if request.method=='POST':
        username = request.POST.get('user_name')
        password = request.POST.get('pwd')
        email = request.POST.get('email')
        if not all([username, password, email]):
            return render(request, 'users/register.html', {'errmsg': '参数不能为空'})
        if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
            return render(request, 'users/register.html', {'errmsg': '邮箱不合法!'})
        try:
            passport = Passport.objects.add_one_passport(username=username, password=password, email=email)
        except:
            return render(request, 'users/register.html', {'errmsg': '用户名已存在！'})
        #生成激活的token itsdangetous
        serializer = Serializer(settings.SECRET_KEY,3600)
        token = serializer.dumps({'confirm':passport.id})
        token = token.decode()

        # 同步/给用户的邮箱发激活邮件
        send_mail('阶梯书城用户激活', '', settings.EMAIL_HOST_USER, [email], html_message='<a href="http://127.0.0.1:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)
        #异步发送激活邮件
        # send_active_email.delay(token,username,email)

        request.session['islogin'] = True
        request.session['username'] = username
        request.session['passport_id'] = passport.id
        return redirect(reverse('books:index'))
    return render(request,'users/register.html',)

'''显示登录页面'''
def login(request):
    if request.COOKIES.get("username"):
        username = request.COOKIES.get("username")
        checked = 'checked'
    else:
        username = ''
        checked = ''
    context = {
        'username': username,
        'checked': checked,
    }
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember = request.POST.get('remember')
        vc = request.POST.get('vc')
        code = request.session.get('verifycode')
        if not all([username,password,vc]) :
            return JsonResponse({'res':2})
        if vc.upper() != code.upper():
            return JsonResponse({'res':3})
        #情况二：账号密码正确，设置session和cookie后，响应传递2个数据：res=1;
        #      redirect_url = 主页路由，给ajax来跳转到主页
        passport = Passport.objects.get_one_passport(username=username,password=password)
        if passport:
            redirect_url =reverse('books:index')
            jres = JsonResponse({'res':1,'redirect_url':redirect_url})

            if remember == 'true':
                jres.set_cookie('username',username,max_age=7*24*3600)
            else:
                jres.delete_cookie('username')

            #记住h用户的登录状态
            request.session['islogin'] = True
            request.session['username'] = username
            request.session['passport_id'] = passport.id
            return jres
        #情况三：账号密码错误，响应返回数据：res=0
        else:
            return JsonResponse({'res':0})
    return render(request, 'users/login.html', context)


'''退出登录，清空session'''
def logout(request):
    request.session.flush()
    return redirect(reverse('books:index'))

'''用户中心'''
@login_required
def center(request):

    passport_id = request.session.get('passport_id')
    addr = Address.objects.get_default_address(passport_id=passport_id)

    # 获取用户的最近浏览信息
    con = get_redis_connection('default')
    key = 'history_%d' % passport_id
    # 取出用户最近浏览的5个商品的id
    history_li = con.lrange(key, 0, 4)
    # 查询数据库,获取用户最近浏览的商品信息
    books_li = []
    for id in history_li:
        books = Books.objects.get_books_by_id(books_id=id)
        books_li.append(books)
    context = {
        'addr':addr,
        'books_li':books_li
    }
    return render(request,'users/user_center_info.html',context)


'''用户地址'''
@login_required
def address(request):
    passport_id = request.session.get('passport_id')
    if request.method == 'POST':
        '''添加收货地址'''
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        recipient_phone = request.POST.get('phone')
        if not all([recipient_addr,recipient_name,recipient_phone,zip_code]):
            return render(request,'users/user_center_site.html',{'errmsg':'参数不能为空'})
        Address.objects.add_one_address(
            passport_id=passport_id,
            recipient_name=recipient_name,
            recipient_addr=recipient_addr,
            zip_code=zip_code,
            recipient_phone=recipient_phone
        )
        return redirect(reverse('user:address'))
    addr = Address.objects.get_default_address(passport_id=passport_id)
    return render(request,'users/user_center_site.html',{'addr':addr,'page':'address'})

'''用户中心订单页'''
@login_required
def order(request,page):
    passport_id = request.session.get('passport_id')
    #查询用户所有订单，返回订单列表
    order_li = OrderInfo.objects.filter(passport_id=passport_id).order_by('-order_id')

    #遍历获取订单的商品信息
    for order in order_li:
        #根据订单id获取所有订单商品列表
        order_id = order.order_id
        order_books_li = OrderGoods.objects.filter(order_id=order_id)

        #计算商品小计amount,给订单商品对象动态增加amount属性
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            order_books.amount = count * price

        #给order订单对象动态添加一个属性———订单商品列表order_books_li
        order.order_books_li = order_books_li

    paginator = Paginator(order_li,3) #每页显示3个订单
    num_pages = paginator.num_pages  #最大页数
    #判断page，默认为1
    if not page or page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)
    #获取page页面订单列表
    order_li = paginator.page(page)

    #根据当前page,控制页面导航条范围pages
    if num_pages < 5:
        pages = range(1,num_pages+1)
    elif page <= 3 :
        pages = range(1,6)
    elif num_pages - page <= 2:
        pages = (num_pages -4 ,num_pages +1)
    else:
        pages = (page-2,page+3)

    context = {
        'order_li' : order_li,
        'pages' : pages,
    }

    return render(request,'users/user_center_order.html',context)

'''验证码'''
def verifycode(request):

    bgcolor = (random.randint(0,255),random.randint(0,255),random.randint(0,255))
    #创建画布
    image = Image.new('RGB',(100,50),color=bgcolor)
    #获取画布中的画笔对象
    draw = ImageDraw.Draw(image)

    font = ImageFont.truetype(os.path.join(BASE_DIR,'Ubuntu-RI.ttf'),25)
    code = ''
    str1 = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    for i in range(4):
        character = random.choice(str1)
        code += character
        filt = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
        draw.text((10+i*20,random.randint(5,15)),character,fill=filt,font=font)

    del draw
    request.session['verifycode'] = code
    #创建缓冲区
    buffer = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    image.save(buffer,'png')
    # 将内存中的图片数据返回给客户端，类型为图片png
    return HttpResponse(buffer.getvalue(),'image/png')

'''用户账户激活'''
def register_active(request, token):
    serializer = Serializer(settings.SECRET_KEY, 3600)
    try:
        info = serializer.loads(token)
        passport_id = info['confirm']
        # 进行用户激活
        passport = Passport.objects.get(id=passport_id)
        passport.is_active = True
        passport.save()
        # 跳转的登录页
        return redirect(reverse('user:login'))
    except SignatureExpired:
        # 链接过期
        return HttpResponse('激活链接已过期')

templates/users/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>阶梯书城-登录</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.ico' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'books:index' %}" class="login_logo"><img src="{% static 'images/logo1.png' %}" style="width: 180px; height: 80px;"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">阶梯书城 · 朝梦想攀登</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
{#					<form method="post">#}
                        {{ errmsg }}
                        {% csrf_token %}
						<input type="text" name="username" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" id="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
                        <input type="text" name="vc" id="vc" class="code_input" placeholder="请输入验证码">
                        <img style="left: 100px;top: 130px;position: absolute" id="verifycode" src="{% url 'user:verifycode' %}" onclick="this.src='{% url 'user:verifycode' %}?'+Math.random()" alt="CheackCode">
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }} >
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="button" id="btnLogin" value="登录" class="input_submit">
{#					</form>#}
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京聪冲信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

templates/users/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>阶梯书城-注册</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/icon.ico' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo1.png' %}" style="width: 220px; height: 90px;"></a>
			<div class="reg_slogan">书籍是实现梦想的阶梯<br/>——鲁迅<br/></div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”阶梯书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
                        {{errmsg}}
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京聪冲信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}阶梯书店——用户中心{% endblock title %}
{% block topfiles %}{% endblock topfiles%}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:center' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
                            {% if addr %}
                                <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
                                <li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无</li>
							    <li><span>联系地址：</span>无</li>
                            {% endif %}

						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
				    <ul class="books_type_list clearfix">
				        {% for books in books_li %}
				            <li>
				                <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
				                <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
{#				                <div class="operate">#}
{#				                    <span class="prize">￥{{ books.price }}</span>#}
{#				                    <span class="unit">{{ books.unite }}</span>#}
{#				                    <a href="#" books_id="{{ books.id }}"  id="add_cart" class="add_books" title="加入购物车"></a>#}
{#				                </div>#}
				            </li>
				        {% endfor %}
				    </ul>
				</div>
		</div>
	</div>


{% endblock %}

templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %} {# 导入自定义过滤器包 #}
{% block title %}阶梯书店——用户中心{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles%}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:center' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_li %}



				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {# 遍历出来的order_books是一个OrderGoods对象 #}
                                {% for order_books in order.order_books_li %}
								<ul class="order_book_list clearfix">					
									<li class="col01"><img src="{% static order_books.books.image %}"></li>
									<li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
									<li class="col03">{{ order_books.count }}</li>
									<li class="col04">{{ order_books.amount }}元</li>
								</ul>
                                {% endfor %}

							</td>
							<td width="15%">{{ order.total_price }}元</td>
							<td width="15%">{{ order.status | order_status }} {# 使用自定义过滤器 #}
                            </td>
                            {% if order.status == 1 %}
                                <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
                            {% elif order.status == 2 %}
                                <td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">待发货</a></td>
                            {% endif %}

						</tr>
					</tbody>
				</table>

            {% endfor %}



				<div class="pagenation">
					{% if order_li.has_previous %} #通过类属性判断是否显示上一页链接
                        <a href="{% url 'user:order'  page=order_li.previous_page_number %}">上一页</a>
                    {% endif %}
                    {% for mypage in pages %}
                        {% if mypage == order_li.number %}
                            <a href="{% url 'user:order' page=mypage %}" class="active">{{ mypage }}</a>
                        {% else %}
                            <a href="{% url 'user:order'  page=mypage %}">{{ mypage }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if  order_li.has_next %}
                        <a href="{% url 'user:order'  page=order_li.next_page_number %}">下一页</a>
                    {% endif %}
				</div>
		</div>
	</div>

{% endblock body %}

{% block bottomfiles%}
    <script>
    $(function () {
        $('.oper_btn').click(function () {
            // 获取订单id和订单的状态
            order_id = $(this).attr('order_id')
            order_status = $(this).attr('order_status')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            var params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
            if (order_status == 1){
                $.post('/order/pay/', params, function (data) {
                    if (data.res == 3){
                        // 把用户引导支付页面
                        window.open(data.pay_url)
                        // 查询用户的支付结果
                        $.post('/order/check_pay/', params, function (data) {
                            if (data.res == 3){
                                alert('支付成功')
                                // 重新刷新页面
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>
{% endblock bottomfiles %}

templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}阶梯书店——用户中心{% endblock title %}
{% block topfiles %}{% endblock topfiles%}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:center' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1%}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						{% if addr %}
						    <dd>{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
					    {% else %}
                            <dd>无</dd>
                        {% endif %}
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'user:address' %}">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}